dataset:  KIBA
task: regression
category: DTA
entry1_file:  ./dataset/KIBA_subset/drug/processed/data.pt
entry2_file:  ./dataset/KIBA_subset/target/processed/data.pt
entry1_seq_file:  ./dataset/KIBA_subset/drug/drug.csv 
entry2_seq_file:  ./dataset/KIBA_subset/target/target.csv 
pair_file:  ./dataset/KIBA_subset/regression/entry_pairs.csv
label_file: ./dataset/KIBA_subset/regression/pair_labels.csv
save_folder: ./output/KIBA/regression
gpus: 0
num_out_dim: 1
